"""empty message

Revision ID: 438cbaff5a96
Revises: 89d15d62a971
Create Date: 2024-12-07 14:00:11.167241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438cbaff5a96'
down_revision = '89d15d62a971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('rank')

    # ### end Alembic commands ###
