"""empty message

Revision ID: 7a1675b176bf
Revises: ca97921d0825
Create Date: 2022-05-11 21:30:09.726769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1675b176bf'
down_revision = 'ca97921d0825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score', 'something')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('something', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
