"""empty message

Revision ID: 89d15d62a971
Revises: 911968521d60
Create Date: 2024-12-07 13:59:10.455293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89d15d62a971'
down_revision = '911968521d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index('game_location_uindex_2')
        batch_op.create_unique_constraint(batch_op.f('uq_game_image'), ['image'])
        batch_op.create_unique_constraint(batch_op.f('uq_game_location'), ['location'])
        batch_op.create_unique_constraint(batch_op.f('uq_game_title'), ['title'])

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_player_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_player_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_player_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_player_email'), type_='unique')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_game_title'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_game_location'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_game_image'), type_='unique')
        batch_op.create_index('game_location_uindex_2', ['location'], unique=1)

    # ### end Alembic commands ###
